### PR TITLE
Android Workflow update

### PR DESCRIPTION
**Pull request by m1ga**
Java version is at 17 already so I've updated Ti to 12.5.1.GA. Perhaps that builds it. 
Locally (Fedora linux, java 17, Ti 12.5.1) it builds find.

### CODE REVIEW

**Comment by m1ga** [comment]
Let's check if it has something todo with the gradle caching...

**Comment by prashantsaini1** [comment]
@m1ga Looks like Gradle / Build Tools got corrupted by dexmaker version changes.

**Comment by m1ga** [comment]
@prashantsaini1 but even if I change it back to the old version it won't build :shrug: Currently I'm testing if it works when switching to a macos action.

**Comment by m1ga** [comment]
crazy...that works. I'll add the gradle cache again. Hopefully it still works and then we are good to go

**Comment by m1ga** [comment]
Ok it works now. I've switched to macos and had to remove the `npm test` as those are failing now in the mac build. The generated file is working fine with hyperloop-examples so we should be good to go here

**Comment by hansemannn** [comment]
We should really not disable tests just to silence the actions - they did work before and the code changes shouldn't have affected them, so we should make sure to include them again.

**Comment by m1ga** [comment]
I'm not sure what happened between the initial PR action https://github.com/tidev/hyperloop.next/actions/runs/11785224772/job/32826029559 which build fine (ubuntu action, all tests ran fine) and then it broke before it was merged.

So maybe the broken workflow has something todo with https://github.com/tidev/hyperloop.next/pull/394 ? as that was merged before my PR was merged and after that the workflow broke

**Comment by hansemannn** [comment]
But the tests ran after the merge and passed, so these changes were fine.

**Comment by m1ga** [comment]
I'll continue the tests in this PR https://github.com/tidev/hyperloop.next/pull/397 so we have at least a passing PR in this one. 

I'm not sure why it all was green before with the new dex version:
Bildschirmfoto_20241129_110143
but once it was merged it failed

**Comment by prashantsaini1** [comment]
I suspect that even with new dex version, the Gradle was picked as still 7.x from the cache, which is why the tests were running fine. 

After the merge, and since cache was disabled, the Gradle 8 may have been downloaded by new dex version which caused this entire issue.

**Comment by m1ga** [comment]
In the log it is always downloading gradle 7.6.1. Gradle 8 will only be used once Ti 12.6.0 is live. That's why there are some warnings in the log that will go away in the future.

Just saw in the other PR that the tests will fail with node 20, so lets see if they will run again when I go back to node 18

**Comment by m1ga** [comment]
there we go: tests are working now again!

**Review by hansemannn — APPROVED** [review]

**Pull request merged**
