### PR TITLE
fix(ios): Fix Unsupported swift architecture

### PR DESCRIPTION
**Pull request by AbdullahFaqeir**
Fix when compiling module
Needed for #391 

FINALY after around 7 hoursl

### CODE REVIEW

**Comment by AbdullahFaqeir** [comment]
@m1ga  @AbdullahFaqeir This was a good day for me

**Comment by m1ga** [comment]
@AbdullahFaqeir nice! Can you please add the .github/actions from https://github.com/tidev/hyperloop.next/pull/391/files so we can see that it is building online

**Comment by AbdullahFaqeir** [comment]
> @AbdullahFaqeir nice! Can you please add the .github/actions from https://gith@nub.com/tidev/hyperloop.next/pull/391/files so we can see that it is building online


@m1ga done

**Comment by m1ga** [comment]
@AbdullahFaqeir I don't see the files in this PR. Can you check it again please

**Comment by AbdullahFaqeir** [comment]
@m1ga 
I'm really sorry but I'm kinda noop when it comes to github actions

**Comment by m1ga** [comment]
no problem! We are almost there :smile: I can push some stuff later so minimize the changes. Happy that you help here to solve the iOS issue!

**Comment by AbdullahFaqeir** [comment]
When can we have it running, I'm really excited, I want to move to the next one hahaah

**Comment by AbdullahFaqeir** [comment]
@m1ga @hansemannn can someone send me the CLA

And I'm proud I fixed it, proud that I'm giving back to you guys, proud of every hour I spent on each PR

**Review by m1ga — APPROVED** [review]
LGTM. Both Android and iOS actions build now :+1: The CLA check is failing because the first commit was not done with the Github user.

@hansemannn please check it and then you can merge this and after that https://github.com/tidev/hyperloop.next/pull/391

Then we can create a new release to use it in the gradle 8 PR :+1:

**Review by hansemannn — APPROVED** [review]

**Pull request merged**
